SMTP_SERVER="smtp.gmail.com:587"
SMTP_FROM=$1
SMTP_USER=$1
SMTP_PASS=$2
EMAIL_DST=$1
SMTP_ASSUNTO="RELATORIO DE ROBO"
MENSAGEM="ROBO FACEBOOK"
ANEXO="*.png"
sendEmail -f $SMTP_USER -t $SMTP_FROM -u $SMTP_ASSUNTO -m $MENSAGEM -s $SMTP_SERVER -xu $SMTP_USER -xp $SMTP_PASS -a $ANEXO

